version: "3.9"
name: railtrail-dev-db
services:
    postgres-dev-db:
        image: postgres:15-alpine
        # restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PWD}
            POSTGRES_DB: ${DB_NAME}
        expose:
            - 5432
        ports:
            - "8095:5432"
        volumes:
            - postgres_db:/var/lib/postgresql/data

volumes:
    postgres_db:
