name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # manual triggering, for debugging purposes

env:
  TEST_TAG: user/app:test

jobs:
  backend-positioning:
    name: Check Positioning Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        working-directory: ./backend/positioning
        run: pip install -r requirements.txt

      - name: Generate schema code
        working-directory: ./dev
        run: python dev.py update --no-website --no-frontend

      - name: Linting
        working-directory: ./backend/positioning
        run: pylint --rcfile=../../pylintrc.toml -j 0 **/*.py

  docker-backend-positioning:
    name: Check Positioning Backend Docker
    runs-on: ubuntu-latest
    needs:
      - backend-positioning
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.positioning
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}

  docker-backend-db-migration:
    name: Check DB Migration Docker
    runs-on: ubuntu-latest
    needs:
      - docker-backend-positioning
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.migration
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}


  backend-website:
    name: Check Website Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./backend/website
        run: npm install

      - name: Generate schema code
        working-directory: ./dev
        run: python dev.py update --no-positioning --no-frontend

      - name: Linting
        working-directory: ./backend/website
        run: npm run lint

  docker-backend-website:
    name: Check Website Backend Docker
    runs-on: ubuntu-latest
    needs:
      - backend-website
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.website
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}


  frontend-website:
    name: Check Website Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Generate schema code
        working-directory: ./dev
        run: python dev.py update --no-website --no-positioning

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Linting
        working-directory: ./frontend
        run: npm run lint
